run:
  timeout: 10m
  issues-exit-code: 1

linters-settings:
  errcheck:
    exclude-functions:
        - io.WriteString
        - (*go.uber.org/zap/buffer.Buffer).WriteString
        - (*go.uber.org/zap/buffer.Buffer).WriteByte

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: util/security/tls.go
      linters:
        - gosec
      text: "G402:"
    - path: util/security/cert.go
      linters:
        - gosec
      text: "G402:"
    - path: pkg/proxy/net/auth.go
      linters:
        - gosec
      text: "G101:|G401:|G505:"
    - path: pkg/util/cmd/cmd.go
      linters:
        - gosec
      text: "G204:"
    - path: ".*.go"
      linters:
        - gosec
      text: "G115:"

linters:
  enable:
    - gosec
    - gofmt
    - goimports
    - misspell
