# options for analysis running
run:
  timeout: 10m
  issues-exit-code: 1

linters-settings:

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters:
  enable:
    - gosec
    - gofmt
    - goimports
    - misspell
