FROM alpine:edge as builder

RUN apk add --no-cache --progress git make go
ARG VERSION
ARG BRANCH
ARG COMMIT
ARG GOPROXY
ADD . /proxy
RUN export GOPROXY=${GOPROXY} && cd /proxy && go mod download -x
RUN export VERSION=${VERSION} && export BRANCH=${BRANCH} && export COMMIT=${COMMIT} && export GOPROXY=${GOPROXY} && cd /proxy && go build ./cmd/replayer

FROM alpine:latest

COPY --from=builder /proxy/replayer /bin/replayer