name: test
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false
  workflow_run:
    workflows:
      - build
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "setup golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: "try to use build cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: "test all"
        run: make test
      - name: "set up tmate session if necessary"
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug }}
        uses: mxschmitt/action-tmate@v3
