name: test
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false
  workflow_run:
    workflows: ["build"]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/common.yml@test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      debug: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug }}
